name: Test

on:
  push:
    branches:
      - main
      - whscullin/actions
  pull_request:

jobs:
  test-all:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "true"
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install
        run: npm ci --loglevel error
      - name: Build and Test
        run: npm run build-prod
